version: 1
formatters:
  simple:
    format: "%(asctime)s %(levelname)8s: [%(name)s]\t%(message)s"
    datefmt: '%Y/%m/%d %H:%M'
  proxy-output:
    format: "%(message)s"
    datefmt: '%Y/%m/%d %H:%M'
  colored:
    (): colorlog.ColoredFormatter
    format: "%(asctime)s %(log_color)s%(levelname)8s%(reset)s: %(cyan)s[%(name)s]%(reset)s %(message)s"
    datefmt: '%Y/%m/%d %H:%M'

handlers:
  file_handler:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    encoding: utf-8
    level: DEBUG
    filename: 哎.log
    maxBytes: 10485760  # 10MB
  console_handler:
    class: logging.StreamHandler
    formatter: colored
    level: DEBUG

root:
  level: DEBUG
  handlers: []

loggers:
  uvicorn.error:
    level: INFO
    handlers: [file_handler]
  uvicorn.access:
    level: INFO
    handlers: [console_handler]
  哎:
    level: DEBUG
    handlers: [console_handler, file_handler]